### PR TITLE
fix: Pass -nosteam to all compile tools

### PR DESCRIPTION
**Pull request by JJL772**
Needs nosteam I think

### CODE REVIEW

**Comment by SCell555** [comment]
Why is this needed?

**Comment by JJL772** [comment]
It tries to mount stuff dynamically with mounts.kv
Does not work in CI

**Comment by SCell555** [comment]
All tools force use the "nosteam" path, so this should not be necessary.

**Comment by JJL772** [comment]
That's not my experience, it seems to still look for mounts and fails if steam isn't open. Maybe I did something wrong though, idk 
Im going to push a release this weekend though, so I'll try to confirm it

**Comment by RealityAnomaly** [comment]
Some tools like mdlcompile actually require steam to load search paths so they can load requisite models from Portal 2. We need to think this one through a bit more carefully.

**Pull request closed without merging**
